name: PDF To Markdown

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Compile markdown
        uses: northy/pdf-to-markdown-workflow@master
        with:
          # Input PDF file
          pdf_input: Mitchell-Arndt-Resume.pdf
          # Output pngs folder
          output_folder: images
          # Source markdown file
          source_md: source.md
          # Output markdown file
          output_md: readme.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
